version: 2

builds:
  - id: matrix
    binary: godotreleaser
    main: ./cmd/godotreleaser
    goos:
      - linux
      - windows
    goarch:
      - amd64
    ignore:
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64
      - goos: linux
        goarch: amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X github.com/ruffel/godotreleaser/internal/cmd/version.version={{ .Summary }}

  - id: docker
    binary: godotreleaser
    main: ./cmd/godotreleaser
    ldflags:
      - -X github.com/ruffel/godotreleaser/internal/cmd/version.version={{ .Summary }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64

archives:
  - format: binary

dockers:
  - id: docker
    image_templates:
      - ghcr.io/ruffel/godotreleaser:{{ .Tag }}
      - ghcr.io/ruffel/godotreleaser:v{{ .Major }}
      - ghcr.io/ruffel/godotreleaser:v{{ .Major }}.{{ .Minor }}
      - ghcr.io/ruffel/godotreleaser:latest
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
    extra_files:
      - scripts/entrypoint.sh

changelog:
  filters:
    exclude:
    - "^ci"
    - "^test"
    - "^chore"
    - "merge conflict"
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
  groups:
  - title: 'New Features'
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 100
  - title: 'Bug fixes'
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 200
  - title: 'Dependency updates'
    regexp: "^.*build\\(deps\\):+.*$"
    order: 300
  - title: "Documentation updates"
    regexp: "^.*docs[(\\w)]*:+.*$"
    order: 400
  - title: "Other work"
    order: 9999
